// Copyright (c) 2015 - 2022 Doozy Entertainment. All Rights Reserved.
// This code can only be used under the standard Unity Asset Store End User License Agreement
// A Copy of the EULA APPENDIX 1 is available at http://unity3d.com/company/legal/as_terms

// ReSharper disable StringLiteralTypo

namespace Doozy.Runtime.Common
{
    public static class TestValues
    {
        public static string[] Cheeses =
        {
            "Halloumi",
            "Gouda",
            "Blue Cheese",
            "Roquefort",
            "Bocconcini",
            "Colby",
            "American",
            "Cheddar",
            "Ricotta",
            "Mozzarella",
            "Parmesan",
            "Chèvre",
            "Burrata",
            "Muenster",
            "Paneer",
            "String Cheese",
            "Parmigiano-Reggiano",
            "Havarti",
            "Limburger",
            "Monterey Jack",
            "Romano",
            "Pepper Jack",
            "Taleggio",
            "Colby-Jack Cheese",
            "Cream Cheese",
            "Manchego",
            "Fresh Mozzarella",
            "Camembert",
            "Jarlsberg",
            "Neufchatel",
            "Swiss",
            "Cheese Curds",
            "Cotija",
            "Cottage Cheese",
            "Gorgonzola",
            "Brie",
            "Gruyere",
            "Feta",
            "Mascarpone",
            "Asiago",
            "Provolone",
            "Emmental",
        };

        public static string[] Fruits =
        {
            "Crab Apple",
            "Salak",
            "Satsuma",
            "Jambul",
            "Magellan Barberry",
            "Tamarind",
            "Cloudberry",
            "Persimmon",
            "Cantaloupe",
            "Pomegranate",
            "Boysenberry",
            "Raspberry",
            "Juniper Berry",
            "Orange",
            "Jabuticaba",
            "Jostaberry",
            "Mango",
            "Surinam Cherry",
            "Gooseberry",
            "Grewia Asiatica",
            "Prune",
            "Lulo",
            "Musk Melon",
            "Avocado",
            "Nance",
            "Kiwifruit",
            "Jujube",
            "Pear",
            "Nectarine",
            "Blackcurrant",
            "Galia Melon",
            "Acerola",
            "Canistel",
            "White Currant",
            "Cranberry",
            "Hala Fruit",
            "Abiu",
            "Honeyberry",
            "Yuzu",
            "Coconut",
            "Kaffir Lime",
            "Tangelo",
            "Cactus Pear",
            "Guava",
            "Feijoa",
            "Purple Mangosteen",
            "Pineberry",
            "Tayberry",
            "Strawberry",
            "Redcurrant",
            "Apple",
            "Damson",
            "Apricot",
            "Black Sapote",
            "Plumcot",
            "Banana",
            "Plantain",
            "Salmonberry",
            "Chico Fruit",
            "Huckleberry",
            "Watermelon",
            "Star Fruit",
            "Tangerine",
            "Elderberry",
            "Rose Apple",
            "Soursop",
            "Mamey Sapote",
            "Ackee",
            "Finger Lime",
            "Kumquat",
            "Marionberry",
            "Passionfruit",
            "Star Apple",
            "Lychee",
            "Coco De Mer",
            "Jackfruit",
            "Quince",
            "African Cucumber",
            "Ugli Fruit",
            "Longan",
            "Cempedak",
            "Currant",
            "Kiwano",
            "Grapefruit",
            "Blood Orange",
            "Melon",
            "Mandarine",
            "Tomato",
            "Raisin",
            "Blueberry",
            "Lime",
            "Plum",
            "Durian",
            "Açaí",
            "Grape",
            "Miracle Fruit",
            "Clementine",
            "Dragonfruit",
            "Goji Berry",
            "Loquat",
            "Peach",
            "Cherry",
            "Pomelo",
            "Rambutan",
            "Papaya",
            "Pineapple",
            "Mangosteen",
            "Japanese Plum",
            "Tamarillo",
            "Bilberry",
            "Mouse Melon",
            "Lemon",
            "Mulberry",
            "Date",
            "Honeydew",
            "Monstera Deliciosa",
            "Salal Berry",
            "Egg Fruit",
            "Blackberry",
            "Loganberry",
            "Fig",
            "Breadfruit",
            "White Sapote",
            "Mamey Apple",
        };

        public static string[] Vegetables =
        {
            "Morel Mushrooms",
            "Cucumbers",
            "Okra",
            "Watercress",
            "Chick Pea",
            "Mangetout",
            "Arrowroot",
            "Collard Greens",
            "Ulluco",
            "Ensete",
            "Beetroot",
            "Sour Cabbage",
            "Canna",
            "Water Chestnut",
            "Mozuku",
            "Chickweed",
            "Lagos Bologi",
            "Broadleaf Arrowhead",
            "Asparagus",
            "Pignut",
            "Wild Leek",
            "Scallion",
            "Daikon",
            "Greater Plantain",
            "Black Radish",
            "Fiddlehead Green",
            "Garlic",
            "Pumpkin",
            "Bell Peppers",
            "Red Leaf Lettuce",
            "Onion",
            "Soybean",
            "Dandelion",
            "Kale",
            "Bok Choy",
            "Kohlrabi",
            "Tigernut",
            "Sea Kale",
            "Florence Fennel",
            "Spinach",
            "Horseradish",
            "Sorrel",
            "Carrot",
            "Radish",
            "Garbanzo",
            "Shallot",
            "Buttercup Squash",
            "Sierra Leone Bologi",
            "Indian Pea",
            "Rapini",
            "Nori",
            "Parsnip",
            "Welsh Onion",
            "Galangal",
            "Lettuce",
            "Sea Beet",
            "Green Soybeans",
            "Celeriac",
            "Arame",
            "Rutabaga",
            "Skirret",
            "Peas",
            "Pigeon Pea",
            "Caper",
            "Yarrow",
            "Eggplant",
            "Squash Blossoms",
            "Nopal",
            "Burdock Roots",
            "Winged Bean",
            "Arracacha",
            "Amaranth",
            "Turnip",
            "Chayote Squash",
            "Prairie Turnip",
            "Water Caltrop",
            "Cauliflower",
            "Salad Savoy",
            "Cardoon",
            "Cassava",
            "Yao Choy",
            "Common Beans",
            "Garden Rocket",
            "Fluted Pumpkin",
            "Arugula",
            "Malabar Spinach",
            "Land Cress",
            "Wasabi",
            "Tatsoi",
            "Turmeric",
            "Chaya",
            "Yam",
            "Broccoflower",
            "Bamboo Shoots",
            "Hijiki",
            "Swede",
            "Earthnut Pea",
            "Guar",
            "Water Spinach",
            "Yukon Gold Potatoes",
            "Kombu",
            "Prussian Asparagus",
            "Pak Choy",
            "Sea Grape",
            "Horse Gram",
            "Zucchini",
            "Cabbage",
            "Dulse",
            "Ginger",
            "Cactus",
            "Summer Squash",
            "Moth Bean",
            "Yuca Root",
            "Hamburg Parsley",
            "Laver",
            "Dolichos",
            "Mashua",
            "Sea Lettuce",
            "Fennel",
            "Tarwi",
            "Tomatillo",
            "Mung Bean",
            "Tepary Bean",
            "Urad Bean",
            "Salsify",
            "Snow Pea",
            "Lemongrass",
            "Adzuki Bean",
            "Samphire",
            "Courgette Flowers",
            "Banana Squash",
            "Celery",
            "Drumstick",
            "Dill",
            "Garlic Chives",
            "Leek",
            "Ricebean",
            "Lotus Root",
            "Chicory",
            "Kurrat",
            "Mushrooms",
            "Elephant Garlic",
            "American Groundnut",
            "Crookneck Squash",
            "Broccolini",
            "Broccoli",
            "Winter Squash",
            "Mizuna",
            "Catsear",
            "Yardlong Bean",
            "Belgian Endive",
            "Mustard Greens",
            "Wheatgrass",
            "Brussel Sprouts",
            "Tomato",
            "Fava bean",
            "Radicchio",
            "Camas",
            "Potato",
            "Celtuce",
            "Cress",
            "Taro",
            "Pearl Onion",
            "Black Eyed Pea",
            "Napa Cabbage",
            "Komatsuna",
            "Endive",
            "Artichoke",
            "Sculpit",
            "Tree Onion",
            "Spring Onion",
            "Green Beans",
            "Good King Henry",
            "Scorzonera",
            "Sweet Potato",
            "Manoa",
            "Dabberlocks",
            "Runner Bean",
            "Elephant Foot Yam",
            "Lentil",
            "Acorn Squash",
            "Paracress",
            "Butternut Squash",
            "Soko",
            "Black Salsify",
            "Aonori",
            "Daylily",
            "Fat Hen",
            "Orache",
            "Ogonori",
            "Golden Samphire",
            "Ramp",
            "Delicata Squash",
            "Lima Bean",
            "Ahipa",
            "Mulukhiyah",
            "Chives",
            "Chrysanthemum",
            "Cherry Tomato",
            "Common Purslane",
            "New Zealand Spinach",
            "Snap Pea",
        };

        public static string[] Pork =
        {
            "Salami",
            "Prosciutto",
            "Hot Dogs",
            "Jamon",
            "Sausages",
            "Bacon",
            "Ham",
        };

        public static string[] Beef =
        {
            "Chuck",
            "Shank",
            "Brisket",
            "Rib",
            "Short Plate",
            "Flank",
            "Loin",
            "Sirloin",
            "The Round",
            "Tongue",
            "Neck",
            "Knuckle",
            "Liver And Other Organ Meats",
        };

        public static string[] Beers =
        {
            "Ale",
            "Lager",
            "Porter",
            "Stout",
            "Blonde Ale",
            "Brown Ales",
            "Pale Ale",
            "India Pale Ale",
            "Wheat",
            "Pilsner",
            "Sour Ale",
        };

        public static string[] WhiteWines =
        {
            "Vernaccia",
            "Marsanne",
            "Muscat",
            "Semillon",
            "Pinot Grigio",
            "Viognier",
            "Gewürztraminer",
            "Sauvignon Blanc",
            "Grüner Veltliner",
            "Pinot Blanc",
            "Chardonnay",
            "Riesling",
            "Malvasia",
        };
        
        public static string[] RedWines =
        {
            "Cabernet Sauvignon",
            "Charbono",
            "Malbec",
            "Petite Sirah",
            "Mourvedre",
            "Dolcetto",
            "Grenache",
            "Cabernet Franc",
            "Carignan",
            "Syrah",
            "Pinot Noir",
            "Zinfandel",
            "Sangiovese",
            "Gamay",
            "Merlot",
            "Nehbyehlas",
            "Barbera",
        };
    }
}
